name = "WebBlast"
uuid = "9f6dbb68-adea-48dd-82a4-058b403bed1f"
authors = ["Ben Murrell"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
julia = "1.4"
DataFrames = "1.2.2"
EzXML = "1.1.0"
HTTP = "0.9.16"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
